# NOTE version is important for mem_limit, no swarm
version: "2"
name: "remix-portal"
services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres

    container_name: "rp-pg"
    env_file: ./.env
    tty: true # Enables debugging capabilities when attached to this container.
    # stdin_open: true
    ports:
      - 5452:5452
    volumes:
      - ../.data/pg:/var/lib/postgresql/data

  web:
    mem_limit: ${WEB_MEM_LIMIT}
    # environment:
    #   - CURRENT_GUID=${CURRENT_GUID}
    #   - CURRENT_UID=${CURRENT_UID}

    build:
      context: .
      dockerfile: ./Dockerfile.nodejs
      args:
        CURRENT_GUID: ${CURRENT_GUID}
        CURRENT_UID: ${CURRENT_UID}
    container_name: "rp-http"
    tty: true # Enables debugging capabilities when attached to this container.

    depends_on:
      - db
    links:
      - db
    command: sh -c '${WEB_CMD}'
    ports:      
      - 3100:3100
    volumes:
      - ../:/app
